<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use App\Models\Data\PohonKinerja;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class PohonKinerjaSeeder extends Seeder
{
    public function run(): void
    {
        $json = '
        [
            {
                "id": 1,
                "name": "TEST",
                "slug": "test",
                "instance_id": 14,
                "file": "storage/images/uploads/1682644360_2mt4mxqj2PuDXiWnZ6KtGOL7wJLM3gReqJ3NwAJn (1).png",
                "file_path": null,
                "description": "TEST AJA",
                "status": "active",
                "created_by": 1,
                "updated_by": null,
                "deleted_at": "2023-06-23 13:43:46",
                "created_at": "2023-04-28 07:44:35",
                "updated_at": "2023-06-23 13:43:46"
            },
            {
                "id": 2,
                "name": "Pohon Kinerja BAPPEDA",
                "slug": "test-2",
                "instance_id": 14,
                "file": "storage/images/uploads/1687503210_POKINFINAL.pdf",
                "file_path": null,
                "description": "Pohon Kinerja BAPPEDA",
                "status": "active",
                "created_by": 8,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-04-28 08:33:10",
                "updated_at": "2023-06-23 13:53:55"
            },
            {
                "id": 3,
                "name": "POHON KINERJA",
                "slug": "pohon-kinerja",
                "instance_id": 24,
                "file": "storage/images/uploads/1687161808_pokin 2.pdf",
                "file_path": null,
                "description": "BALITBANGDA",
                "status": "active",
                "created_by": 47,
                "updated_by": null,
                "deleted_at": "2023-06-21 12:14:39",
                "created_at": "2023-06-19 15:03:28",
                "updated_at": "2023-06-21 12:14:39"
            },
            {
                "id": 4,
                "name": "Pohon Kinerja BPKAD",
                "slug": "pohon-kinerja-bpkad",
                "instance_id": 9,
                "file": "storage/images/uploads/1688958898_POKINBPKAD2023FINAL.pdf",
                "file_path": null,
                "description": "BPKAD tahun 2023",
                "status": "active",
                "created_by": 48,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-06-21 10:45:49",
                "updated_at": "2023-07-10 10:14:58"
            },
            {
                "id": 5,
                "name": "POHON KINERJA BALITBANGDA",
                "slug": "pohon-kinerja-balitbangda",
                "instance_id": 24,
                "file": "storage/images/uploads/1687324652_POHONKINERJA BALITBANGDA.pdf",
                "file_path": null,
                "description": "POHON KINERJA BALITBANGDA",
                "status": "active",
                "created_by": 47,
                "updated_by": null,
                "deleted_at": "2023-06-21 12:52:15",
                "created_at": "2023-06-21 12:17:32",
                "updated_at": "2023-06-21 12:52:15"
            },
            {
                "id": 6,
                "name": "POHON KINERJA",
                "slug": "pohon-kinerja",
                "instance_id": 24,
                "file": "storage/images/uploads/1687326783_POHONKINERJABALITBANGDA.pdf",
                "file_path": null,
                "description": "POHON KINERJA",
                "status": "active",
                "created_by": 47,
                "updated_by": null,
                "deleted_at": "2023-06-22 09:48:42",
                "created_at": "2023-06-21 12:53:03",
                "updated_at": "2023-06-22 09:48:42"
            },
            {
                "id": 7,
                "name": "POHON KINERJA BALITBANGDA",
                "slug": "pohon-kinerja-balitbangda",
                "instance_id": 24,
                "file": "storage/images/uploads/1687402164_POHONKINERJABALITBANGDA.pdf",
                "file_path": null,
                "description": "POHON KINERJA BALITBANGDA",
                "status": "active",
                "created_by": 47,
                "updated_by": null,
                "deleted_at": "2023-07-21 15:19:44",
                "created_at": "2023-06-22 09:49:24",
                "updated_at": "2023-07-21 15:19:44"
            },
            {
                "id": 8,
                "name": "POHON KINERJA",
                "slug": "pohon-kinerja",
                "instance_id": 1,
                "file": "storage/images/uploads/1688359179_PohonKinerjaDisdikbud2021-2026UPLOADDISICARAM.pdf",
                "file_path": null,
                "description": "DINAS PENDIDIKAN DAN KEBUDAYAAN",
                "status": "active",
                "created_by": 17,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-07-03 11:39:39",
                "updated_at": "2023-07-03 11:39:39"
            },
            {
                "id": 9,
                "name": "Pohon Kinerja",
                "slug": "pohon-kinerja",
                "instance_id": 16,
                "file": "storage/images/uploads/1688968606_Pohonkinerjadisperkimtan2023oke.pdf",
                "file_path": null,
                "description": "Dinas Perkimtan Kabupaten Ogan Ilir",
                "status": "active",
                "created_by": 14,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-07-10 12:56:46",
                "updated_at": "2023-07-10 12:56:46"
            },
            {
                "id": 10,
                "name": "Pohon Kinerja Dinas Pemuda, Olahraga dan Pariwisata Kabupaten Ogan Ilir",
                "slug": "pohon-kinerja-dinas-pemuda-olahraga-dan-pariwisata-kabupaten-ogan-ilir",
                "instance_id": 12,
                "file": "storage/images/uploads/1689216456_p_o_h_o_n_k_i_n_e_r_j_a_d_i_s_p_o_r_p_a2021-2026.pdf",
                "file_path": null,
                "description": "Pohon Kinerja DISPORPA",
                "status": "active",
                "created_by": 54,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-07-11 14:06:05",
                "updated_at": "2023-07-13 09:47:36"
            },
            {
                "id": 11,
                "name": "POHON KINERJA",
                "slug": "pohon-kinerja",
                "instance_id": 27,
                "file": "storage/images/uploads/1689063616_p_o_h_o_n_k_i_n_e_r_j_a_d_i_n_a_s_p_e_r_i_k_a_n_a_n.pdf",
                "file_path": null,
                "description": "DINAS PERIKANAN",
                "status": "active",
                "created_by": 50,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-07-11 15:20:16",
                "updated_at": "2023-07-11 15:20:16"
            },
            {
                "id": 12,
                "name": "Pohon Kinerja Dinas Komunikasi Informatika Statistik dan Persandian",
                "slug": "pohon-kinerja-dinas-komunikasi-informatika-statistik-dan-persandian",
                "instance_id": 4,
                "file": "storage/images/uploads/1689132787_pohon_kinerja_d_inas_komunikasi_informatika_statistik_dan_persandian_kab._ogan_ilir.pdf",
                "file_path": null,
                "description": "Pohon kinerja Dinas Komunikasi Informatika Statistik dan Persandian Kabupaten Ogan Ilir meliputi 3 urusan yaitu urusan komunikasi dan informatika, urusan statistik dan urusan persandian",
                "status": "active",
                "created_by": 58,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-07-12 10:33:07",
                "updated_at": "2023-07-12 10:33:07"
            },
            {
                "id": 13,
                "name": "Pohon Kinerja",
                "slug": "pohon-kinerja",
                "instance_id": 26,
                "file": "storage/images/uploads/1689139150_pokin_b_k_p_s_d_m.png",
                "file_path": null,
                "description": "BKPSDM",
                "status": "active",
                "created_by": 24,
                "updated_by": null,
                "deleted_at": "2023-07-18 11:14:02",
                "created_at": "2023-07-12 12:19:10",
                "updated_at": "2023-07-18 11:14:02"
            },
            {
                "id": 14,
                "name": "Pohon kinerja ",
                "slug": "pohon-kinerja",
                "instance_id": 46,
                "file": "storage/images/uploads/1689146000_rev2._pohon_kinerja_damkar2023.pdf",
                "file_path": null,
                "description": "Dinas Pemadam Kebakaran dan Penyelamatan Kabupaten Ogan Ilir",
                "status": "active",
                "created_by": 22,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-07-12 14:13:20",
                "updated_at": "2023-07-12 14:13:20"
            },
            {
                "id": 15,
                "name": "POHON KINERJA KECAMATAN LUBUK KELIAT",
                "slug": "pohon-kinerja-kecamatan-lubuk-keliat",
                "instance_id": 36,
                "file": "storage/images/uploads/1689442031_p_o_h_o_n_k_i_n_e_r_j_a_l_u_b_u_k_k_e_l_i_a_t2023.pdf",
                "file_path": null,
                "description": "Pohon Kinerja Kecamatan Lubuk Keliat Tahun 2023",
                "status": "active",
                "created_by": 28,
                "updated_by": null,
                "deleted_at": "2023-07-16 00:32:13",
                "created_at": "2023-07-16 00:27:11",
                "updated_at": "2023-07-16 00:32:13"
            },
            {
                "id": 16,
                "name": "POHON KINERJA",
                "slug": "pohon-kinerja",
                "instance_id": 36,
                "file": "storage/images/uploads/1689443092_p_o_h_o_n_k_i_n_e_r_j_a_l_u_b_u_k_k_e_l_i_a_t2023.pdf",
                "file_path": null,
                "description": "Pohon Kinerja Kecamatan Lubuk Keliat Tahun 2023",
                "status": "active",
                "created_by": 28,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-07-16 00:44:52",
                "updated_at": "2023-07-16 00:44:52"
            },
            {
                "id": 17,
                "name": "POHON KINERJA BKPSDM",
                "slug": "pohon-kinerja-bkpsdm",
                "instance_id": 26,
                "file": "storage/images/uploads/1689656514_pokin_bkpsdm._i_i-_copy.pdf",
                "file_path": null,
                "description": "BKPSDM",
                "status": "active",
                "created_by": 24,
                "updated_by": null,
                "deleted_at": "2023-07-18 13:26:34",
                "created_at": "2023-07-18 12:01:54",
                "updated_at": "2023-07-18 13:26:34"
            },
            {
                "id": 18,
                "name": "POHON KINERJA BKPSDM",
                "slug": "pohon-kinerja-bkpsdm",
                "instance_id": 26,
                "file": "storage/images/uploads/1689661668_pokin_bkpsdm._i_i-_revisi.pdf",
                "file_path": null,
                "description": "BKPSDM",
                "status": "active",
                "created_by": 24,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-07-18 13:27:48",
                "updated_at": "2023-07-18 13:27:48"
            },
            {
                "id": 19,
                "name": "POHON KINERJA BALITBANGDA KABUPATEN OGAN ILIR",
                "slug": "pohon-kinerja-balitbangda-kabupaten-ogan-ilir",
                "instance_id": 24,
                "file": "storage/images/uploads/1689927161_p_o_h_o_n_k_i_n_e_r_j_a_b_a_l_i_t_b_a_n_g_d_a_o_i.pdf",
                "file_path": null,
                "description": "POHON KINERJA BALITBANGDA",
                "status": "active",
                "created_by": 47,
                "updated_by": null,
                "deleted_at": "2023-07-21 15:13:32",
                "created_at": "2023-07-21 15:12:41",
                "updated_at": "2023-07-21 15:13:32"
            },
            {
                "id": 20,
                "name": "POHON KINERJA BALITBANGDA KABUPATEN OGAN ILIR",
                "slug": "pohon-kinerja-balitbangda-kabupaten-ogan-ilir",
                "instance_id": 24,
                "file": "storage/images/uploads/1689927562_p_o_h_o_n_k_i_n_e_r_j_a_b_a_l_i_t_b_a_n_g_d_a.pdf",
                "file_path": null,
                "description": "POHON KINERJA BALITBANGDA",
                "status": "active",
                "created_by": 47,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-07-21 15:19:22",
                "updated_at": "2023-07-21 15:19:22"
            },
            {
                "id": 21,
                "name": "POHON KINERJA KECAMATAN INDRALAYA",
                "slug": "pohon-kinerja-kecamatan-indralaya",
                "instance_id": 37,
                "file": "storage/images/uploads/1690002366_p_o_h_o_n_k_i_n_e_r_j_a_k_e_c_i_n_d_r_a_l_a_y_a__o_k_page-0001.jpg",
                "file_path": null,
                "description": "Pohon Kinerja adalah alat bantu bagi organisasi untuk mengawal struktur logika sebab-akibat atas berbagai kondisi yang diperlukan organisasi dalam menghasilkan outcome yang diinginkan",
                "status": "active",
                "created_by": 31,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-07-22 12:06:06",
                "updated_at": "2023-07-22 12:06:06"
            },
            {
                "id": 22,
                "name": "POHON KINERJA KECAMATAN PEMULUTAN",
                "slug": "pohon-kinerja-kecamatan-pemulutan",
                "instance_id": 40,
                "file": "storage/images/uploads/1690175703_pohon_kinereja_baru.pdf",
                "file_path": null,
                "description": "POHON KINERJA KECAMATAN PEMULUTAN TAHUN ANGGARAN 2022 - 2026",
                "status": "active",
                "created_by": 40,
                "updated_by": null,
                "deleted_at": "2023-07-26 09:30:47",
                "created_at": "2023-07-24 12:15:03",
                "updated_at": "2023-07-26 09:30:47"
            },
            {
                "id": 23,
                "name": "POHON KINERJA KECAMATAN INDRALAYA UTARA",
                "slug": "pohon-kinerja-kecamatan-indralaya-utara",
                "instance_id": 45,
                "file": "storage/images/uploads/1690175794_p_o_h_o_n-_k_i_n_e_r_j_a-_k_e_c.-_i_n_d_r_a_l_a_y_a-_u_t_a_r_a.jpg",
                "file_path": null,
                "description": "Pohon Kinerja Kecamatan Indralaya Utara",
                "status": "active",
                "created_by": 33,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-07-24 12:16:34",
                "updated_at": "2023-07-24 12:16:34"
            },
            {
                "id": 24,
                "name": "POHON KINERJA KECAMATAN RANTAU ALAI",
                "slug": "pohon-kinerja-kecamatan-rantau-alai",
                "instance_id": 34,
                "file": "storage/images/uploads/1690176016_p_o_h_o_n_k_i_n_e_r_j_a_r_a_n_t_a_u_a_l_a_i_page-0001.jpg",
                "file_path": null,
                "description": "Alat bantu bagi organisasi Untuk Mengawal  Struktur Logika Sebab akibat atas berbagai kondisi yang di perlukan organisasi dalam menghasilkan outcame yang di inginkan",
                "status": "active",
                "created_by": 96,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-07-24 12:20:16",
                "updated_at": "2023-07-24 12:20:16"
            },
            {
                "id": 25,
                "name": "Pohon Kinerja RSUD Revisi",
                "slug": "pohon-kinerja-rsud-revisi",
                "instance_id": 13,
                "file": "storage/images/uploads/1691988766_p_o_k_i_n_r_s_u_d.png",
                "file_path": null,
                "description": "pohon kinerja RSUD menunjang visi, misi dan IKU kabupaten",
                "status": "active",
                "created_by": 44,
                "updated_by": null,
                "deleted_at": "2024-03-21 13:30:26",
                "created_at": "2023-07-24 13:36:33",
                "updated_at": "2024-03-21 13:30:26"
            },
            {
                "id": 26,
                "name": "Pohon Kinerja Badan Pendapatan Daerah",
                "slug": "pohon-kinerja-badan-pendapatan-daerah",
                "instance_id": 21,
                "file": "storage/images/uploads/1690183425_p_o_h_o_n_k_i_n_e_r_j_a_b_a_p_e_n_d_a2023(2).pdf",
                "file_path": null,
                "description": "Pohon Kinerja Badan Pendapatan Daerah",
                "status": "active",
                "created_by": 49,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-07-24 14:23:45",
                "updated_at": "2023-07-24 14:23:45"
            },
            {
                "id": 27,
                "name": "POHON KINERJA DINAS PERHUBUNGAN KABUPATEN OGAN ILIR",
                "slug": "pohon-kinerja-dinas-perhubungan-kabupaten-ogan-ilir",
                "instance_id": 8,
                "file": "storage/images/uploads/1690183882_p_o_h_o_n_k_i_n_e_r_j_a_d_i_s_h_u_b.pdf",
                "file_path": null,
                "description": "MELAKSANAKAN URUSAN PEMERINTAHAN BIDANG PERHUBUNGAN DALAM MENINGKATKAN SISTEM LAYANAN TRANSPORTASI DAERAH",
                "status": "active",
                "created_by": 59,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-07-24 14:31:22",
                "updated_at": "2023-07-24 14:31:22"
            },
            {
                "id": 28,
                "name": "Pohon Kinerja Dinas Lingkungan Hidup",
                "slug": "pohon-kinerja-dinas-lingkungan-hidup",
                "instance_id": 10,
                "file": "storage/images/uploads/1690253245_pohon_kinerja_dinas_l_h_o_i2023_fix16_juni.pdf",
                "file_path": null,
                "description": "Pohon Kinerja",
                "status": "active",
                "created_by": 52,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-07-25 09:47:25",
                "updated_at": "2023-07-25 09:47:25"
            },
            {
                "id": 29,
                "name": "Pohon Kinerja Dinas Ketahanan Pangan dan Pertanian Kabupaten Ogan Ilir",
                "slug": "pohon-kinerja-dinas-ketahanan-pangan-dan-pertanian-kabupaten-ogan-ilir",
                "instance_id": 6,
                "file": "storage/images/uploads/1690256840_revisi_pohon_kinerja_dinas_k_p_perta2023.pdf",
                "file_path": null,
                "description": "Revisi Pohon Kinerja Dinas Ketahanan Pangan dan Pertanian Kabupaten Ogan Ilir Tahun 2023",
                "status": "active",
                "created_by": 53,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-07-25 10:47:20",
                "updated_at": "2023-07-25 10:47:20"
            },
            {
                "id": 30,
                "name": "POHON KINERJA BPBD TAHUN 2023",
                "slug": "pohon-kinerja-bpbd-tahun-2023",
                "instance_id": 17,
                "file": "storage/images/uploads/1690948182_p_o_k_i_n_b_p_b_d_t_a_h_u_n2023.pdf",
                "file_path": null,
                "description": "Pohon kinerja BPBD disusun berdasarkan PERMENPAN dan RB NO 89 Tahun 2021 Tentang Perjenjangan Instansi Pemerintah yang digunakana untuk membantu bagi organisasi BPBD Kabupaten Ogan Ilir untuk mengawal struktur logika sebab-akibat atas berbagai kondisi yang diperlukan BPBD dalam menghasilkan outcome yang diinginkan.",
                "status": "active",
                "created_by": 104,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-08-02 10:49:42",
                "updated_at": "2023-08-02 10:49:42"
            },
            {
                "id": 31,
                "name": "POHON KINERJA KECAMATAN SUNGAI PINANG",
                "slug": "pohon-kinerja-kecamatan-sungai-pinang",
                "instance_id": 31,
                "file": "storage/images/uploads/1691160741_p_o_h_o_n_k_i_n_e_r_j_a_k_e_c_s_u_n_g_a_i_p_i_n_a_n_g_page-0001.jpg",
                "file_path": null,
                "description": "alat bantu bagi organisasi untuk mengawal struktur logika sebab-akibat atas berbagai kondisi yang diperlukan organisasi dalam menghasilkan outcome yang diinginkan.",
                "status": "active",
                "created_by": 38,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-08-04 21:52:21",
                "updated_at": "2023-08-04 21:52:21"
            },
            {
                "id": 32,
                "name": "Pohon Kinerja Satpol PP",
                "slug": "pohon-kinerja-satpol-pp",
                "instance_id": 23,
                "file": "storage/images/uploads/1691455650_pohon_kinerja.pdf",
                "file_path": null,
                "description": "Ketenteraman dan Ketertiban Umum, Penegakan Perda dan Perbup serta Perlindungan Masyarakat",
                "status": "active",
                "created_by": 18,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-08-08 07:47:30",
                "updated_at": "2023-08-08 07:47:30"
            },
            {
                "id": 33,
                "name": "POHON KINERJA URUSAN BIDANG PERPUSTAKAAN",
                "slug": "pohon-kinerja",
                "instance_id": 42,
                "file": "storage/images/uploads/1691469573_p_o_h_o_n_k_i_n_e_r_j_a_r_e_v_i_s_i_p_e_r_p_u_s_t_a_k_a_a_n.pdf",
                "file_path": null,
                "description": "Urusan Bidang Perpustakaan",
                "status": "active",
                "created_by": 34,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-08-08 11:39:33",
                "updated_at": "2023-08-08 11:40:14"
            },
            {
                "id": 34,
                "name": "POHON KINERJA URUSAN BIDANG KEARSIPAN",
                "slug": "pohon-kinerja-urusan-bidang-kearsipan",
                "instance_id": 42,
                "file": "storage/images/uploads/1691469658_p_o_k_i_n_a_r_s_i_p_t_e_r_b_a_r_u.pdf",
                "file_path": null,
                "description": "Urusan Bidang Kearsipan",
                "status": "active",
                "created_by": 34,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-08-08 11:40:58",
                "updated_at": "2023-08-08 11:40:58"
            },
            {
                "id": 35,
                "name": "Pohon Kinerja Dinas Perindustrian, Perdagangan, Koperasi dan UKM",
                "slug": "pohon-kinerja-dinas-perindustrian-perdagangan-koperasi-dan-ukm",
                "instance_id": 19,
                "file": "storage/images/uploads/1692073304_pohon_kinerja_disperindagkop_u_k_m_rev90.pdf",
                "file_path": null,
                "description": "Pohon Kinerja Dinas Perindustrian, Perdagangan, Koperasi dan UKM",
                "status": "active",
                "created_by": 55,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-08-15 11:21:44",
                "updated_at": "2023-08-15 11:21:44"
            },
            {
                "id": 36,
                "name": "Pohon Kinerja Sekretariat Daerah",
                "slug": "pohon-kinerja-sekretariat-daerah",
                "instance_id": 15,
                "file": "storage/images/uploads/1692161490_p_o_h_o_n_k_i_n_e_r_j_a_setda.pdf",
                "file_path": null,
                "description": "Pohon Kinerja Sekretariat Daerah",
                "status": "active",
                "created_by": 45,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-08-16 11:51:30",
                "updated_at": "2023-08-16 11:51:30"
            },
            {
                "id": 37,
                "name": "Pohon Kinerja Dinas Kesehatan Tahun 2023",
                "slug": "pohon-kinerja-dinas-kesehatan-tahun-2023",
                "instance_id": 3,
                "file": "storage/images/uploads/1692587767_p_o_k_i_n_p_d_f2023_t_e_r_b_a_r_u.pdf",
                "file_path": null,
                "description": "penjabaran kinerja dan indikator kinerja yang lebih terperinci atau kondisi-kondisi yang mempengaruhinya dengan menggunakan kerangka logis di Dinas Kesehatan",
                "status": "active",
                "created_by": 19,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-08-21 10:16:07",
                "updated_at": "2023-08-21 10:16:07"
            },
            {
                "id": 38,
                "name": "Pohon Kinerja PUPR ",
                "slug": "pohon-kinerja-pupr",
                "instance_id": 22,
                "file": "storage/images/uploads/1696995933_pohon_kinerja_p_u_p_r202327092023.pdf",
                "file_path": null,
                "description": "Pohon KInerja PUPR Tahun 2023",
                "status": "active",
                "created_by": 56,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2023-10-11 10:45:33",
                "updated_at": "2023-10-11 10:45:33"
            },
            {
                "id": 39,
                "name": "POHON KINERJA RSUD KAB. OGAN ILIR",
                "slug": "pohon-kinerja-rsud-kab-ogan-ilir",
                "instance_id": 13,
                "file": "storage/images/uploads/1711002616_p_o_h_o_n_k_i_n_e_r_j_a_r_s_u_d_k_a_b._o_g_a_n_i_l_i_r.pdf",
                "file_path": null,
                "description": "POHON KINERJA RSUD KAB. OGAN ILIR",
                "status": "active",
                "created_by": 44,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2024-03-21 13:30:16",
                "updated_at": "2024-03-21 13:30:16"
            },
            {
                "id": 40,
                "name": "POHON KINERJA RSUD KAB. OGAN ILIR",
                "slug": "pohon-kinerja-rsud-kab-ogan-ilir",
                "instance_id": 13,
                "file": "storage/images/uploads/1717469356_p_o_h_o_n_k_i_n_e_r_j_a_r_s_u_d_k_a_b._o_g_a_n_i_l_i_r.pdf",
                "file_path": null,
                "description": "POHON KINERJA RSUD KAB. OGAN ILIR",
                "status": "active",
                "created_by": 44,
                "updated_by": null,
                "deleted_at": null,
                "created_at": "2024-06-04 09:49:16",
                "updated_at": "2024-06-04 09:49:16"
            }
        ]';

        $json = json_decode($json, true);

        foreach ($json as $pohon) {
            // dd($pohon);
            $data = new PohonKinerja();
            $data->periode_id = 1;
            $data->instance_id = $pohon['instance_id'];
            $data->name = $pohon['name'];
            $data->description = $pohon['description'];
            $file = $pohon['file'];
            $file = Str::remove('storage/images/uploads/', $file);
            $file = 'storage/pohon-kinerja/' . $file;
            $data->file = $pohon['file'];
            $data->status = $pohon['status'];
            $data->created_by = $pohon['created_by'];
            $data->updated_by = $pohon['updated_by'];
            $data->updated_at = $pohon['updated_at'];
            $data->created_at = $pohon['created_at'];
            $data->deleted_at = $pohon['deleted_at'];
            $data->save();
        }
    }
}
